config/routes.rb
Digihack::Application.routes.draw do
  get "memberships/create"

  devise_for :users
  resources :projects

  resources :projects do
    resources :memberships, only: [:create, :destroy]
    resources :comments
  end

  root :to => 'projects#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :body, :commenter
  belongs_to :project
end

app/models/membership.rb
class Membership < ActiveRecord::Base
  belongs_to :user
  belongs_to :project
  attr_accessible :user_id, :project_id
end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :creator, :class_name => 'User', :foreign_key => 'creator_id'
  has_many :memberships, dependent: :destroy
  has_many :members, :class_name => 'User', :through => :memberships, :source => :user
  has_many :comments, dependent: :destroy

  attr_accessible :description, :title

  validates :title, :presence => true
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :name, :presence => { :message => 'cannot be blank' }

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name

  has_many :projects
  has_many :memberships

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @project = Project.find(params[:project_id])
    @comment = @project.comments.new(params[:comment])
    @comment.commenter = current_user.name
    @comment.save

    redirect_to project_path(@project)
  end
end

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController
  def create
    logger.debug "Params: #{params}"
    logger.debug "Current user: #{current_user}"
    @project = Project.find(params[:project_id])
    @membership = @project.memberships.create(user_id: current_user.id)
    @membership.save
    
    redirect_to project_path(@project), notice: 'Successfully added as project member.'
  end

  def destroy
  	@user = User.find(params[:id])
  	@project = Project.find(params[:project_id])
  	@membership = Membership.find_by_user_id_and_project_id(@user.id, @project.id)
  	@membership.delete

  	redirect_to project_path(@project), notice: 'Successfully removed as member from project.'
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  before_filter :authenticate_user!, :except => [:index, :show]

  # GET /projects
  def index
    @projects = Project.all

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  # GET /projects/1
  def show
    @project = Project.find(params[:id])
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
    @project = Project.find(params[:id])
  end

  # POST /projects
  def create
    @project = Project.new(params[:project])
    @project.creator = current_user

    if @project.save
      redirect_to @project, notice: 'Project was successfully created.'
    else
      render action: "new"
    end
  end

  # PUT /projects/1
  def update
    @project = Project.find(params[:id])

    if @project.creator != current_user
      redirect_to @project, notice: 'This project is not yours to edit.'
    elsif @project.update_attributes(params[:project])
      redirect_to @project, notice: 'Project was successfully updated.'
    else
      render action: "edit"
    end
  end

  # DELETE /projects/1
  def destroy
    @project = Project.find(params[:id])

    # if @project.creator != current_user
    #   flash[:notice] = 'That project is not yours to delete'
    #   redirect_to :back
    # else
      @project.destroy
      redirect_to projects_url
    # end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/memberships_helper.rb
module MembershipsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Digihack</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">

  <div class="navbar">
    <div class="navbar-inner">
      <%= link_to 'Digihack', root_path, class: 'brand' %>
      <ul class="nav">
        <li><%= link_to 'Projects', projects_path %></li>
      </ul>
      <ul class="nav pull-right">
        <% if user_signed_in? -%>
          <li><a href="#">Signed in as <%= current_user.email %></a></li>
          <li><%= link_to 'Sign out', destroy_user_session_path, :method => :delete %></li>  
        <% else %>
          <li><%= link_to 'Sign up', new_user_registration_path %></li>
          <li><%= link_to 'Sign in', new_user_session_path %></li>
        <% end %>
      </ul>
    </div>
  </div>

  <div id="flash">
    <% if notice %>
      <p class="alert"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert"><%= alert %></p>
    <% end %>
  </div>

  <div id="content">
    <%= yield %>
  </div>

</body>
</html>

app/views/memberships/create.html.erb
<h1>Memberships#create</h1>
<p>Find me in app/views/memberships/create.html.erb</p>

app/views/projects/_form.html.erb
<%= form_for @project, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :title, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :title, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :description, :class => 'text_area' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                projects_path, :class => 'btn' %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<%- model_class = Project -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/projects/index.html.erb
<%- model_class = Project -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <% if @projects.count > 0 %>
    <thead>
      <tr>
        <th><%= model_class.human_attribute_name(:title) %></th>
        <th><%= model_class.human_attribute_name(:description) %></th>
        <th><%= model_class.human_attribute_name(:creator_id) %></th>
        <th><%=t '.actions', :default => t("helpers.actions") %></th>
      </tr>
    </thead>
    <tbody>
      <% @projects.each do |project| %>
        <tr>
          <td width="20%"><%= link_to project.title, project_path(project) %></td>
          <td width="50%"><%= truncate project.description, length: 140 %></td>
          <td width="10%"><%= project.creator.name %></td>
          <td width="20%">
          <%= link_to 'View', project_path(project), :class => 'btn btn-mini' %>
            <% if project.creator == current_user %>
              <%= link_to t('.edit', :default => t("helpers.links.edit")),
                          edit_project_path(project), :class => 'btn btn-mini' %>
              <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                          project_path(project),
                          :method => :delete,
                          :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                          :class => 'btn btn-mini btn-danger' %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  <% else %>
    <h3>No Projects Yet!</h3>
    <p>Be the first to create a project below</p>
  <% end %>
</table>

<%= link_to 'Create A New Project',
            new_project_path,
            :class => 'btn btn-primary' %>

app/views/projects/new.html.erb
<%- model_class = Project -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/projects/show.html.erb
<%- model_class = Project -%>
<div class="page-header">
  <h1><%= @project.title %></h1>
  <p><strong>Created by:</strong> <%= @project.creator.name %></p>
  <% if @project.creator == current_user %>
    <p>
      <%= link_to t('.edit', :default => t("helpers.links.edit")),
                  edit_project_path(@project), :class => 'btn' %>
      <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                  project_path(@project),
                  :method => 'delete',
                  :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                  :class => 'btn btn-danger' %>
    </p>
  <% end %>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= simple_format(@project.description) %></dd>
</dl>

<div class="form-actions">
  <h3>
    <span>Project Members</span>
    <span>
      <% if current_user %>
        <% if @project.members.include?(current_user) %>
          <%= link_to 'Remove Self From Project',
                      project_membership_path(@project.id, current_user.id),
                      :method => 'delete',
                      :data => { :confirm => 'Are you sure?' },
                      :class => 'btn btn-danger pull-right' %>
        <% else %>
          <%= link_to 'Become a member of this project',
                      project_memberships_path(@project),
                      :method => :post,
                      :class => 'btn btn-success pull-right' %>      
        <% end %>
      <% end %>      
    </span>  
  </h3>
  <ul>
    <% if @project.members.count > 0 %>
      <% @project.members.each do |user| %>
        <li><%= user.name %></li>
      <% end %>
    <% else %>
      <li>No members yet!</li>
    <% end %>
  </ul>
</div>

<div>
  <h3>Comments</h3>
  <table class="table table-striped">
    <tbody>
      <% if @project.comments.count > 0 %>
        <% @project.comments.each do |comment| %>
          <tr>
          <td width="30%"><strong><%= comment.commenter %></strong></td>
          <td width="70%"><%=  simple_format(comment.body) %></td>
          </tr>
        <% end %>
      <% else %>
        <tr><td width="100%">No Comments Yet!</td></tr>
      <% end %>
    </tbody>
  </table>
  <br />
  <% if current_user %>
    <%= form_for([@project, @project.comments.build]) do |f| %>
      <%= f.text_area :body %>
      <%= f.submit :class => 'btn' %> 
    <% end %>
  <% end %>
</div>